from odoo import api, fields, models

MCP_KEY_NAME = "AI MCP Connector"


class ResUsersApikeys(models.Model):
    """Add MCP visibility helpers to native Odoo API keys.

    Keys generated by the Connect-to-Claude wizard are named ``AI MCP Connector
    (Claude)``; the Connections admin view filters on that so it only shows
    MCP connections, never unrelated RPC keys.
    """

    _inherit = "res.users.apikeys"

    mcp_last_used = fields.Datetime(
        string="Last Used (MCP)", compute="_compute_mcp_last_used",
        help="Most recent successful MCP tool call by this key's user.",
    )

    def _compute_mcp_last_used(self):
        Log = self.env["ai.mcp.log"].sudo()
        for rec in self:
            last = Log.search(
                [("user_id", "=", rec.user_id.id), ("event_type", "=", "model_access")],
                order="create_date desc", limit=1)
            rec.mcp_last_used = last.create_date if last else False

    def action_mcp_revoke(self):
        """Revoke (delete) the selected MCP key(s). Admin-only via the menu."""
        self.sudo().unlink()
        return {"type": "ir.actions.client", "tag": "soft_reload"}
