# -*- coding: utf-8 -*-
{
    'name': "Price Intelligence",
    'summary': """
        Module to consult sales prices suggested by the intelligence system.
    """,
    'description': """
        This module provides a view to analyze price predictions generated by a Machine Learning
        pipeline, in an isolated manner without affecting existing product modelss.
    """,
    'author': "Wayakit",
    'website': "https://www.yourcompany.com",
    'category': 'Sales',
    'version': '17.0.1.0.0',
    'license': 'LGPL-3',
    'depends': ['base', 'sales_team'],
    'data': [
        'security/price_intelligence_security.xml',
        'security/ir.model.access.csv',
        'data/product_industry_data.xml',
        'data/product_subindustry_data.xml',
        'views/product_price_suggestion_views.xml',
        'views/product_master_views.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
    'icon': '/price_intelligence/static/description/icon.png',
}