# -*- coding: utf-8 -*-
{
    'name': "Price Intelligence",
    'summary': """
        Module to consult sales prices suggested by the intelligence system.
    """,
    'description': """
        This module provides a view to analyze price predictions generated by a Machine Learning
        pipeline, in an isolated manner without affecting existing product models.
    """,
    'author': "Wayakit",
    'website': "https://www.yourcompany.com",
    'category': 'Sales',
    'version': '17.0.1.0.0',
    # AQUÍ ESTÁ EL CAMBIO:
    'depends': ['base', 'sales_team'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_price_suggestion_views.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}